apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "proj-gr4"
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mortenlyngosenquist/frontend:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: "proj-gr4"
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
    
      
      
